# Generated by Django 2.2 on 2020-02-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('website', models.URLField()),
                ('tag', models.CharField(choices=[('College Visit', 'College Visit'), ('Volunteer', 'Volunteer'), ('DBCR', 'DBCR'), ('Professional Development', 'Professional Development'), ('Religious', 'Religious')], max_length=50)),
            ],
        ),
    ]
