# Generated by Django 2.2 on 2020-05-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trequest',
            old_name='zip',
            new_name='zipCode',
        ),
    ]
