# Generated by Django 2.2 on 2020-05-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_requests', '0002_auto_20200506_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tRequest',
            new_name='Requests',
        ),
    ]
