# Generated by Django 2.2 on 2020-05-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_requests', '0003_auto_20200506_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
