# Generated by Django 2.2 on 2020-05-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_requests', '0004_auto_20200506_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='needDate',
            field=models.DateTimeField(),
        ),
    ]
