# Generated by Django 2.2 on 2020-05-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_requests', '0005_auto_20200508_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='needDate',
            field=models.CharField(max_length=100),
        ),
    ]
