# Generated by Django 2.2 on 2021-01-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
        ),
    ]
